python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml --fringe-factor 1 -p 6.0 -o osm.pedestrian.trips.xml -r osm.pedestrian.rou.xml -e 3600 --vehicle-class pedestrian --pedestrians --prefix ped --max-distance 2000 --validate
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml --fringe-factor 1 -p 6.0 -o osm.person.trips.xml -r osm.person.rou.xml -e 3600 --vehicle-class pedestrian --persontrips --prefix per --trip-attributes "modes=\"public\""  --validate
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml --fringe-factor 2 -p 5.0 -o osm.bicycle.trips.xml -r osm.bicycle.rou.xml -e 3600 --vehicle-class bicycle --vclass bicycle --prefix bike --fringe-start-attributes "departSpeed=\"max\"" --max-distance 8000 --trip-attributes "departLane=\"best\"" --validate
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml --fringe-factor 2 -p 5.0 -o osm.motorcycle.trips.xml -r osm.motorcycle.rou.xml -e 3600 --vehicle-class motorcycle --vclass motorcycle --prefix moto --fringe-start-attributes "departSpeed=\"max\"" --max-distance 1200 --trip-attributes "departLane=\"best\"" --validate
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml --fringe-factor 5 -p 3.0 -o osm.passenger.trips.xml -r osm.passenger.rou.xml -e 3600 --vehicle-class passenger --vclass passenger --prefix veh --min-distance 300 --trip-attributes "departLane=\"best\"" --fringe-start-attributes "departSpeed=\"max\"" --allow-fringe.min-length 1000 --lanes --validate
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml --fringe-factor 5 -p 3.0 -o osm.truck.trips.xml -r osm.truck.rou.xml -e 3600 --vehicle-class truck --vclass truck --prefix truck --min-distance 600 --fringe-start-attributes "departSpeed=\"max\"" --trip-attributes "departLane=\"best\"" --validate
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml --fringe-factor 5 -p 40.0 -o osm.bus.trips.xml -r osm.bus.rou.xml -e 3600 --vehicle-class bus --vclass bus --prefix bus --min-distance 600 --fringe-start-attributes "departSpeed=\"max\"" --trip-attributes "departLane=\"best\"" --validate
:: not needed anymore, since trams are included in public transport route file python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml --fringe-factor 20 -p 19.952489 -o osm.tram.trips.xml -r osm.tram.rou.xml -e 3600 --vehicle-class tram --vclass tram --prefix tram --fringe-start-attributes "departSpeed=\"max\"" --min-distance 1200 --trip-attributes "departLane=\"best\"" --validate
python "%SUMO_HOME%\tools\randomTrips.py" -n osm.net.xml --fringe-factor 40 -p 40.0 -o osm.ship.trips.xml -r osm.ship.rou.xml -e 3600 --vehicle-class ship --vclass ship --prefix ship --validate --fringe-start-attributes "departSpeed=\"max\""
